[settings]
experimental = true

[tools]
rust = { version = "latest", profile = "default" }
"ubi:cargo-bins/cargo-binstall" = "latest"
mkcert = "latest"
"aqua:nextest-rs/nextest/cargo-nextest" = "latest"
"aqua:rhysd/actionlint" = "latest"
"aqua:protocolbuffers/protobuf/protoc" = "latest"
bun = "latest"
"cargo:cargo-sort" = "latest"
node = "latest"
"npm:wrangler" = "latest"
"cargo:worker-build" = "latest"
"ubi:j178/prefligit" = "latest"

[env]
_.file = ".dev.vars"
