[settings]
experimental = true

[tools]
rust = { version = "latest", profile = "default", components = "llvm-tools,rust-analyzer" }
"ubi:cargo-bins/cargo-binstall" = "latest"
mkcert = "latest"
"aqua:nextest-rs/nextest/cargo-nextest" = "latest"
"aqua:rhysd/actionlint" = "latest"
"aqua:protocolbuffers/protobuf/protoc" = "latest"
bun = "latest"
"cargo:cargo-sort" = "latest"
"ubi:j178/prek" = "0.0.23"
"cargo:cargo-hakari" = "latest"

[env]
_.file = ".env"
KUZU_SHARED = "1"
