[settings]
experimental = true

[tools]
rust = { version = "latest", profile = "default" }
"aqua:cargo-bins/cargo-binstall" = "latest"
mkcert = "latest"
"aqua:nextest-rs/nextest/cargo-nextest" = "latest"
"aqua:rhysd/actionlint" = "latest"
"aqua:protocolbuffers/protobuf/protoc" = "latest"
bun = "latest"
"cargo:j178/prefligit" = "rev:781b6ac45ca84350682d34ed2312914abd15e31f"
"cargo:cargo-sort" = "latest"
node = "latest"

[env]
_.file = ".dev.vars"
