
[workspace]
members = ["crates/*"]
resolver = "3"
[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
async-openai = { git = "https://github.com/casualjim/async-openai", branch = "reqwest-middleware", default-features = false, features = [
  "rustls-webpki-roots",
] }
async-trait = "0.1"

color-eyre = "0.6"

dotenvy = "0.15"

eyre = "0.6"

futures = "0.3"
opentelemetry = { version = "0.30.0", features = ["trace"] }

reqwest = { version = "0.12.15", default-features = false, features = [
  "rustls-tls",
  "json",
  "stream",
  "http2",
  "charset",
  "macos-system-configuration",
  "brotli",
  "gzip",
  "deflate",
  "zstd",
] }
reqwest-middleware = "0.4.2"
reqwest-retry = "0.7.0"
reqwest-tracing = { version = "0.5.8", features = ["opentelemetry_0_30"] }

schemars = { version = "1.0.4", features = ["chrono", "either", "uuid"] }
serde = "1.0.219"
serde_json = "1.0.141"

thiserror = "2.0.12"

tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"
tracing = { version = "0.1.41" }
typed-builder = "0.21.0"

uuid = { version = "1.17.0", features = ["js", "serde", "v7"] }

validator = { version = "0.20.0", features = ["derive"] }

[profile.release]
opt-level = 3
lto = "thin"
incremental = true
