#!/usr/bin/env bash

#MISE description="Format Slipstream code files"

proj_dir=$(git rev-parse --show-toplevel)
cd "$proj_dir" || exit 1

biome format --write

# Enable globstar for recursive globbing
shopt -s globstar
rustfmt --edition 2024 crates/**/*.rs
