[package]
name = "slipstream-restate"
version.workspace = true
edition.workspace = true

[dependencies]
restate-sdk.workspace = true
tokio.workspace = true
eyre.workspace = true
serde.workspace = true
serde_json.workspace = true
rand.workspace = true
tracing-subscriber.workspace = true
schemars.workspace = true
