#!/usr/bin/env bash

#MISE description="Test Slipstream (release)"

proj_dir=$(git rev-parse --show-toplevel)
cd "$proj_dir" || exit 1

cargo nextest run --workspace --release --no-fail-fast --no-capture
