services:
  wasmcloud:
    image: wasmcloud/wasmcloud:latest
    environment:
      RUST_LOG: debug,hyper=info,async_nats=info,oci_client=info,cranelift_codegen=warn
      WASMCLOUD_LOG_LEVEL: debug
      WASMCLOUD_RPC_HOST: nats
      WASMCLOUD_CTL_HOST: nats
      WASMCLOUD_ALLOW_FILE_LOAD: "true"
      WASMCLOUD_OCI_ALLOWED_INSECURE: registry:5000
      WASMCLOUD_OBSERVABILITY_ENABLED: "false"
    ports:
      - "127.0.0.1:8000-8100:8000-8100" # Expose ports 8000-8100 for examples that use an HTTP server

  wadm:
    depends_on:
      - "nats"
    image: ghcr.io/wasmcloud/wadm:latest
    environment:
      - WADM_NATS_SERVER=nats
