[package]
name = "slipstream-core"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
typed-builder.workspace = true
uuid.workspace = true
