[package]
name = "slipstream-core"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
base64.workspace = true
dashmap.workspace = true
eyre.workspace = true
jiff.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
typed-builder.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio.workspace = true
