#!/usr/bin/env bash

set -eu -o pipefail

#MISE description="Lint Slipstream Javascript/Typescript"
#MISE sources=["**/*.js", "**/*.ts", "**/*.tsx", "**/*.jsx", "**/*.json", "**/*.jsonc", "**/*.css", "**/*.graphql"]

echo "🔎 Linting Javascript/Type code with biome..."
proj_dir=$(git rev-parse --show-toplevel)
cd "$proj_dir" || exit 1

biome check "$@"
echo "✅ Javascript/Typescript linting complete!"
